version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: deare-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" # 포트 세팅 필요
    networks:
      - deare-net

  redis:
    image: redis:7-alpine
    container_name: deare-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379" # 포트 세팅 필요
    networks:
      - deare-net

  app:
    image: ${APP_IMAGE}
    container_name: deare-backend
    restart: always
    env_file:
      - .env.prod
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080" # 포트 세팅 필요
    networks:
      - deare-net

networks:
  deare-net:

volumes:
  mysql_data:
  redis_data:
