spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

decorator:
  datasource:
    p6spy:
      enable-logging: false

# to-do
# redis-host/port
# db-url/app-user
# oauth redirect-uri